<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Service::upsert([
            [
                'id' => 1,
                'category_id' => 1,
                'name' => 'Gesicht kompl.',
                'short_code' => 'GES',
                'duration' => 30,
                'price' => 109.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 14:50:14',
            ],
            [
                'id' => 2,
                'category_id' => 1,
                'name' => 'Intimzone Frau',
                'short_code' => 'IZ',
                'duration' => 30,
                'price' => 99.00,
                'deleted_at' => '2021-10-11 13:59:26',
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2021-10-11 13:59:26',
            ],
            [
                'id' => 3,
                'category_id' => 1,
                'name' => 'Kotletten',
                'short_code' => 'KOTL',
                'duration' => 30,
                'price' => 59.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 14:50:20',
            ],
            [
                'id' => 4,
                'category_id' => 1,
                'name' => 'Wangenkontur',
                'short_code' => 'WA',
                'duration' => 30,
                'price' => 59.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 14:50:27',
            ],
            [
                'id' => 5,
                'category_id' => 1,
                'name' => 'Pofalte Frau',
                'short_code' => 'POF',
                'duration' => 30,
                'price' => 79.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 14:55:11',
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'name' => 'Oberlippe',
                'short_code' => 'OL',
                'duration' => 30,
                'price' => 49.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 14:55:36',
            ],
            [
                'id' => 7,
                'category_id' => 1,
                'name' => 'Kinn',
                'short_code' => 'KI',
                'duration' => 30,
                'price' => 49.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 14:55:44',
            ],
            [
                'id' => 8,
                'category_id' => 1,
                'name' => 'Augenbrauen / Stirn',
                'short_code' => 'STI',
                'duration' => 30,
                'price' => 59.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 14:55:54',
            ],
            [
                'id' => 9,
                'category_id' => 1,
                'name' => 'Bart',
                'short_code' => 'BAR',
                'duration' => 30,
                'price' => 109.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-06-15 17:04:15',
            ],
            [
                'id' => 10,
                'category_id' => 1,
                'name' => 'Hals',
                'short_code' => 'HAL',
                'duration' => 30,
                'price' => 59.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 14:56:19',
            ],
            [
                'id' => 11,
                'category_id' => 1,
                'name' => 'Achselzone',
                'short_code' => 'AZ',
                'duration' => 30,
                'price' => 59.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 14:58:00',
            ],
            [
                'id' => 12,
                'category_id' => 1,
                'name' => 'Unterarme',
                'short_code' => 'UA',
                'duration' => 30,
                'price' => 119.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 14:59:37',
            ],
            [
                'id' => 13,
                'category_id' => 1,
                'name' => 'Bauch (komplett)',
                'short_code' => 'BAU',
                'duration' => 30,
                'price' => 129.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 14:59:12',
            ],
            [
                'id' => 14,
                'category_id' => 1,
                'name' => 'Brust Mann',
                'short_code' => 'BM',
                'duration' => 30,
                'price' => 129.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 14:59:20',
            ],
            [
                'id' => 15,
                'category_id' => 1,
                'name' => 'Hände',
                'short_code' => 'HAN',
                'duration' => 30,
                'price' => 59.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 15:00:39',
            ],
            [
                'id' => 16,
                'category_id' => 1,
                'name' => 'Gesäß inkl. Pofalte',
                'short_code' => 'PO/POF',
                'duration' => 30,
                'price' => 149.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-06-15 17:06:27',
            ],
            [
                'id' => 17,
                'category_id' => 1,
                'name' => 'Medianlinie',
                'short_code' => 'ML',
                'duration' => 30,
                'price' => 59.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 15:01:08',
            ],
            [
                'id' => 18,
                'category_id' => 1,
                'name' => 'Rücken (komplett)',
                'short_code' => 'RU',
                'duration' => 30,
                'price' => 179.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2022-11-30 10:52:28',
            ],
            [
                'id' => 19,
                'category_id' => 1,
                'name' => 'Brustwarzen',
                'short_code' => 'BW',
                'duration' => 30,
                'price' => 49.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 15:02:20',
            ],
            [
                'id' => 20,
                'category_id' => 1,
                'name' => 'Bikinizone',
                'short_code' => 'BZ',
                'duration' => 30,
                'price' => 69.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:03',
                'updated_at' => '2023-03-01 15:02:35',
            ],
            [
                'id' => 21,
                'category_id' => 1,
                'name' => 'Schultern Mann',
                'short_code' => 'SCH',
                'duration' => 30,
                'price' => 109.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-03-01 15:02:59',
            ],
            [
                'id' => 22,
                'category_id' => 1,
                'name' => 'Oberarme',
                'short_code' => 'OA',
                'duration' => 30,
                'price' => 119.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-03-01 15:16:57',
            ],
            [
                'id' => 23,
                'category_id' => 1,
                'name' => 'Oberkörper',
                'short_code' => 'OK',
                'duration' => 60,
                'price' => 399.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-04-04 12:46:45',
            ],
            [
                'id' => 24,
                'category_id' => 1,
                'name' => 'Nacken',
                'short_code' => 'NA',
                'duration' => 15,
                'price' => 69.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-03-01 15:04:15',
            ],
            [
                'id' => 25,
                'category_id' => 1,
                'name' => 'Oberschenkel',
                'short_code' => 'OS',
                'duration' => 30,
                'price' => 159.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-03-01 15:04:32',
            ],
            [
                'id' => 26,
                'category_id' => 1,
                'name' => 'Unterschenkel',
                'short_code' => 'US',
                'duration' => 30,
                'price' => 149.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-03-01 15:17:25',
            ],
            [
                'id' => 27,
                'category_id' => 1,
                'name' => 'Füße',
                'short_code' => 'FUS',
                'duration' => 30,
                'price' => 59.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-03-01 15:05:31',
            ],
            [
                'id' => 28,
                'category_id' => 1,
                'name' => 'Erweitert',
                'short_code' => 'ERW',
                'duration' => 0,
                'price' => 49.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2022-11-22 18:58:20',
            ],
            [
                'id' => 29,
                'category_id' => 1,
                'name' => 'Sonstige',
                'short_code' => 'SON',
                'duration' => 30,
                'price' => 1.00,
                'deleted_at' => '2021-04-13 16:57:31',
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2021-04-13 16:57:31',
            ],
            [
                'id' => 30,
                'category_id' => 1,
                'name' => 'Teilweise',
                'short_code' => 'TLW',
                'duration' => 15,
                'price' => 1.00,
                'deleted_at' => '2021-04-13 16:57:35',
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2021-04-13 16:57:35',
            ],
            [
                'id' => 31,
                'category_id' => 1,
                'name' => 'Unterkörper',
                'short_code' => 'UK',
                'duration' => 90,
                'price' => 399.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-04-04 12:46:56',
            ],
            [
                'id' => 32,
                'category_id' => 1,
                'name' => 'Brustwarzen',
                'short_code' => 'BF',
                'duration' => 30,
                'price' => 49.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-04-05 15:03:17',
            ],
            [
                'id' => 33,
                'category_id' => 1,
                'name' => 'Intim- und Bikinizone Frau',
                'short_code' => 'IZ, BZ',
                'duration' => 30,
                'price' => 119.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-04-04 12:13:13',
            ],
            [
                'id' => 34,
                'category_id' => 1,
                'name' => 'Gesäß/Po Frau',
                'short_code' => 'PO',
                'duration' => 30,
                'price' => 119.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-09-09 10:31:44',
            ],
            [
                'id' => 35,
                'category_id' => 7,
                'name' => 'Kosmetik',
                'short_code' => 'KOS',
                'duration' => 60,
                'price' => 99.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2021-04-08 15:23:15',
            ],
            [
                'id' => 36,
                'category_id' => 7,
                'name' => 'Kosmetik Beratung',
                'short_code' => 'KOB',
                'duration' => 30,
                'price' => 0.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2022-01-20 15:08:36',
            ],
            [
                'id' => 37,
                'category_id' => 3,
                'name' => 'Narbe',
                'short_code' => 'UNA',
                'duration' => 30,
                'price' => 199.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2022-01-20 15:00:00',
            ],
            [
                'id' => 41,
                'category_id' => 4,
                'name' => 'Tattoo Klein',
                'short_code' => 'TAkl',
                'duration' => 30,
                'price' => 99.00,
                'deleted_at' => '2021-09-30 14:26:13',
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2021-09-30 14:26:13',
            ],
            [
                'id' => 42,
                'category_id' => 4,
                'name' => 'Tattoo Mittel',
                'short_code' => 'TAmi',
                'duration' => 30,
                'price' => 149.00,
                'deleted_at' => '2021-09-30 14:26:17',
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2021-09-30 14:26:17',
            ],
            [
                'id' => 43,
                'category_id' => 4,
                'name' => 'Tattoo Groß',
                'short_code' => 'TAgr',
                'duration' => 30,
                'price' => 149.00,
                'deleted_at' => '2021-09-30 14:26:21',
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2021-09-30 14:26:21',
            ],
            [
                'id' => 44,
                'category_id' => 4,
                'name' => 'Tattoo Steiß (Geweih)',
                'short_code' => 'TAst',
                'duration' => 30,
                'price' => 359.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-02-10 11:37:34',
            ],
            [
                'id' => 45,
                'category_id' => 6,
                'name' => 'Pigmente Gesicht wenige',
                'short_code' => 'Pigm G',
                'duration' => 30,
                'price' => 298.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2022-11-30 10:55:39',
            ],
            [
                'id' => 46,
                'category_id' => 6,
                'name' => 'Pigmente Gesicht komplett',
                'short_code' => 'PigmGk',
                'duration' => 30,
                'price' => 399.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-12-01 13:25:23',
            ],
            [
                'id' => 47,
                'category_id' => 6,
                'name' => 'Pigmentfleck einzeln',
                'short_code' => 'Pigm',
                'duration' => 30,
                'price' => 98.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2022-11-22 15:13:02',
            ],
            [
                'id' => 48,
                'category_id' => 6,
                'name' => 'Pigmente Körper',
                'short_code' => 'PigmK',
                'duration' => 30,
                'price' => 398.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2022-11-30 10:55:54',
            ],
            [
                'id' => 49,
                'category_id' => 6,
                'name' => 'Pigmente Körper viele',
                'short_code' => 'PigmKv',
                'duration' => 30,
                'price' => 798.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2022-11-30 10:56:01',
            ],
            [
                'id' => 50,
                'category_id' => 9,
                'name' => 'Couperose Gesicht',
                'short_code' => 'COU',
                'duration' => 30,
                'price' => 169.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2022-11-30 10:56:12',
            ],
            [
                'id' => 51,
                'category_id' => 8,
                'name' => 'BauchKryo',
                'short_code' => 'BA/HUE',
                'duration' => 30,
                'price' => 269.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2022-11-30 10:56:20',
            ],
            [
                'id' => 52,
                'category_id' => 8,
                'name' => 'Reiterhose/Oberschenkel/Arme',
                'short_code' => 'RH/OS/A',
                'duration' => 30,
                'price' => 299.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2022-11-30 10:56:27',
            ],
            [
                'id' => 53,
                'category_id' => 1,
                'name' => 'Oberlippe/Kinn',
                'short_code' => 'OL/KI',
                'duration' => 30,
                'price' => 69.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-07-03 16:12:53',
            ],
            [
                'id' => 54,
                'category_id' => 1,
                'name' => 'Steißbein Frau',
                'short_code' => 'SBF',
                'duration' => 30,
                'price' => 89.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-03-01 15:09:05',
            ],
            [
                'id' => 55,
                'category_id' => 1,
                'name' => 'oberer Rücken',
                'short_code' => 'ORU',
                'duration' => 30,
                'price' => 159.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2022-11-30 10:56:51',
            ],
            [
                'id' => 56,
                'category_id' => 4,
                'name' => 'Tattoo Klein',
                'short_code' => 'PiTAki',
                'duration' => 30,
                'price' => 159.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-02-10 11:37:54',
            ],
            [
                'id' => 57,
                'category_id' => 4,
                'name' => 'Tattoo Mittel',
                'short_code' => 'PiTAmi',
                'duration' => 30,
                'price' => 219.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-02-10 11:37:06',
            ],
            [
                'id' => 58,
                'category_id' => 4,
                'name' => 'Tattoo Groß',
                'short_code' => 'PiTAgr',
                'duration' => 30,
                'price' => 299.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:04',
                'updated_at' => '2023-02-10 11:38:10',
            ],
            [
                'id' => 59,
                'category_id' => 4,
                'name' => 'Tattoo Laser Steiß',
                'short_code' => 'PiTAst',
                'duration' => 30,
                'price' => 498.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:05',
                'updated_at' => '2022-11-30 10:56:59',
            ],
            [
                'id' => 60,
                'category_id' => 17,
                'name' => 'Entfernung eines Gefäßes',
                'short_code' => 'EeG',
                'duration' => 30,
                'price' => 99.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:05',
                'updated_at' => '2023-11-30 16:00:45',
            ],
            [
                'id' => 61,
                'category_id' => 17,
                'name' => 'Besenreiser (netzartig)',
                'short_code' => 'BR(n)',
                'duration' => 30,
                'price' => 199.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:05',
                'updated_at' => '2022-11-30 10:57:17',
            ],
            [
                'id' => 62,
                'category_id' => 17,
                'name' => 'Besenreiser Oberschenkel komplett',
                'short_code' => 'BROS',
                'duration' => 30,
                'price' => 279.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:05',
                'updated_at' => '2022-11-30 10:57:24',
            ],
            [
                'id' => 63,
                'category_id' => 17,
                'name' => 'Besenreiser Unterschenkel komplett',
                'short_code' => 'BRUS',
                'duration' => 30,
                'price' => 269.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:05',
                'updated_at' => '2022-11-30 10:57:31',
            ],
            [
                'id' => 64,
                'category_id' => 17,
                'name' => 'Besenreiser Beine komplett',
                'short_code' => 'BRBK',
                'duration' => 60,
                'price' => 499.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:05',
                'updated_at' => '2022-11-30 10:57:43',
            ],
            [
                'id' => 65,
                'category_id' => 9,
                'name' => 'Teleangiektasien Gesicht / Nase',
                'short_code' => 'BRGN',
                'duration' => 30,
                'price' => 139.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:05',
                'updated_at' => '2022-11-30 10:57:55',
            ],
            [
                'id' => 66,
                'category_id' => 9,
                'name' => 'Rosacea',
                'short_code' => 'BRR',
                'duration' => 30,
                'price' => 139.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:05',
                'updated_at' => '2022-11-30 10:58:03',
            ],
            [
                'id' => 67,
                'category_id' => 9,
                'name' => 'Couperose',
                'short_code' => 'BRC',
                'duration' => 30,
                'price' => 169.00,
                'deleted_at' => null,
                'created_at' => '2021-04-08 14:38:05',
                'updated_at' => '2022-11-30 10:58:24',
            ],
            [
                'id' => 68,
                'category_id' => 5,
                'name' => 'Unterspritzung Hyal',
                'short_code' => 'USHY',
                'duration' => 30,
                'price' => 319.00,
                'deleted_at' => null,
                'created_at' => '2021-04-12 15:48:35',
                'updated_at' => '2022-11-30 10:58:30',
            ],
            [
                'id' => 69,
                'category_id' => 5,
                'name' => 'Unterspritzung Botox',
                'short_code' => 'USBX',
                'duration' => 30,
                'price' => 199.00,
                'deleted_at' => null,
                'created_at' => '2021-04-12 18:22:21',
                'updated_at' => '2022-11-30 10:58:38',
            ],
            [
                'id' => 70,
                'category_id' => 3,
                'name' => 'Fibrome',
                'short_code' => 'FIB',
                'duration' => 30,
                'price' => 600.00,
                'deleted_at' => null,
                'created_at' => '2021-04-12 18:23:10',
                'updated_at' => '2022-01-20 15:04:18',
            ],
            [
                'id' => 71,
                'category_id' => 7,
                'name' => 'Microdermabrasion 60 Pen',
                'short_code' => 'MIC6',
                'duration' => 60,
                'price' => 99.00,
                'deleted_at' => null,
                'created_at' => '2021-04-12 22:08:59',
                'updated_at' => '2023-11-08 14:44:44',
            ],
            [
                'id' => 72,
                'category_id' => 7,
                'name' => 'MicroNeedling 60 Pen',
                'short_code' => 'MIN6',
                'duration' => 60,
                'price' => 199.00,
                'deleted_at' => null,
                'created_at' => '2021-04-12 22:10:25',
                'updated_at' => '2023-11-08 14:44:56',
            ],
            [
                'id' => 73,
                'category_id' => 8,
                'name' => 'Lymphdrainage',
                'short_code' => 'LY',
                'duration' => 30,
                'price' => 89.00,
                'deleted_at' => null,
                'created_at' => '2021-04-13 16:36:34',
                'updated_at' => '2023-05-05 17:32:23',
            ],
            [
                'id' => 74,
                'category_id' => 8,
                'name' => 'Kryopolyse',
                'short_code' => 'KR',
                'duration' => 30,
                'price' => 0.00,
                'deleted_at' => '2022-11-22 19:01:04',
                'created_at' => '2021-04-13 16:39:03',
                'updated_at' => '2022-11-22 19:01:04',
            ],
            [
                'id' => 75,
                'category_id' => 8,
                'name' => 'Vanqish Me',
                'short_code' => 'VM',
                'duration' => 45,
                'price' => 0.00,
                'deleted_at' => '2022-11-22 19:01:09',
                'created_at' => '2021-04-13 16:39:35',
                'updated_at' => '2022-11-22 19:01:09',
            ],
            [
                'id' => 76,
                'category_id' => 8,
                'name' => 'Fett-Weg-Spritze 1 Spritze',
                'short_code' => 'FWS1',
                'duration' => 30,
                'price' => 169.00,
                'deleted_at' => null,
                'created_at' => '2021-04-13 16:40:05',
                'updated_at' => '2023-07-12 18:50:29',
            ],
            [
                'id' => 77,
                'category_id' => 8,
                'name' => 'Fett-Weg-Spritze 3 Spritzen ',
                'short_code' => 'FWS3',
                'duration' => 30,
                'price' => 399.00,
                'deleted_at' => null,
                'created_at' => '2021-04-13 16:45:36',
                'updated_at' => '2023-07-12 18:51:49',
            ],
            [
                'id' => 78,
                'category_id' => 7,
                'name' => 'Hydrafacial 90',
                'short_code' => 'HF9',
                'duration' => 90,
                'price' => 199.00,
                'deleted_at' => null,
                'created_at' => '2021-04-13 16:48:21',
                'updated_at' => '2022-11-30 10:59:52',
            ],
            [
                'id' => 79,
                'category_id' => 7,
                'name' => 'Hydrafacial 60',
                'short_code' => 'HF6',
                'duration' => 60,
                'price' => 139.00,
                'deleted_at' => null,
                'created_at' => '2021-04-13 16:49:07',
                'updated_at' => '2022-11-30 11:01:43',
            ],
            [
                'id' => 80,
                'category_id' => 7,
                'name' => 'Fruchtsäurepeeling',
                'short_code' => 'FSP',
                'duration' => 15,
                'price' => 20.00,
                'deleted_at' => null,
                'created_at' => '2021-04-13 16:49:44',
                'updated_at' => '2022-11-30 11:02:05',
            ],
            [
                'id' => 81,
                'category_id' => 7,
                'name' => 'Maniküre',
                'short_code' => 'MK',
                'duration' => 60,
                'price' => 55.00,
                'deleted_at' => null,
                'created_at' => '2021-04-13 16:50:58',
                'updated_at' => '2022-11-30 11:02:38',
            ],
            [
                'id' => 82,
                'category_id' => 7,
                'name' => 'Pediküre',
                'short_code' => 'PK',
                'duration' => 60,
                'price' => 69.00,
                'deleted_at' => null,
                'created_at' => '2021-04-13 16:52:03',
                'updated_at' => '2022-11-30 11:02:45',
            ],
            [
                'id' => 83,
                'category_id' => 7,
                'name' => 'Augenbrauen',
                'short_code' => 'AB',
                'duration' => 30,
                'price' => 12.00,
                'deleted_at' => null,
                'created_at' => '2021-04-13 16:52:58',
                'updated_at' => '2022-11-30 11:02:59',
            ],
            [
                'id' => 84,
                'category_id' => 7,
                'name' => 'Wimpern',
                'short_code' => 'WI',
                'duration' => 30,
                'price' => 19.00,
                'deleted_at' => null,
                'created_at' => '2021-04-13 16:53:54',
                'updated_at' => '2022-11-30 11:03:05',
            ],
            [
                'id' => 85,
                'category_id' => 7,
                'name' => 'Massage',
                'short_code' => 'MA',
                'duration' => 60,
                'price' => 85.00,
                'deleted_at' => null,
                'created_at' => '2021-04-13 16:54:23',
                'updated_at' => '2022-11-30 11:03:14',
            ],
            [
                'id' => 86,
                'category_id' => 7,
                'name' => 'Waxing',
                'short_code' => 'WA',
                'duration' => 30,
                'price' => 50.00,
                'deleted_at' => null,
                'created_at' => '2021-04-13 16:55:05',
                'updated_at' => '2022-11-30 11:03:33',
            ],
            [
                'id' => 87,
                'category_id' => 1,
                'name' => 'Ganzkörper',
                'short_code' => 'GK',
                'duration' => 120,
                'price' => 599.00,
                'deleted_at' => null,
                'created_at' => '2021-04-14 11:10:59',
                'updated_at' => '2023-04-04 12:12:27',
            ],
            [
                'id' => 88,
                'category_id' => 3,
                'name' => 'Mirconeedling Gesicht ',
                'short_code' => 'MN',
                'duration' => 60,
                'price' => 349.00,
                'deleted_at' => null,
                'created_at' => '2021-04-14 11:20:31',
                'updated_at' => '2023-07-03 16:24:07',
            ],
            [
                'id' => 89,
                'category_id' => 3,
                'name' => 'Co2 Gesicht',
                'short_code' => 'CO',
                'duration' => 60,
                'price' => 529.00,
                'deleted_at' => null,
                'created_at' => '2021-04-14 11:20:52',
                'updated_at' => '2023-05-05 17:28:07',
            ],
            [
                'id' => 91,
                'category_id' => 3,
                'name' => 'Fraxel',
                'short_code' => 'FX',
                'duration' => 60,
                'price' => 429.00,
                'deleted_at' => null,
                'created_at' => '2021-04-15 09:50:53',
                'updated_at' => '2023-05-05 17:28:41',
            ],
            [
                'id' => 92,
                'category_id' => 1,
                'name' => 'Medianlinie',
                'short_code' => 'MED',
                'duration' => 30,
                'price' => 49.00,
                'deleted_at' => null,
                'created_at' => '2021-04-15 15:22:16',
                'updated_at' => '2023-04-05 14:47:43',
            ],
            [
                'id' => 93,
                'category_id' => 3,
                'name' => 'Schwangerschaftsstreifen',
                'short_code' => 'SCHW',
                'duration' => 60,
                'price' => 599.00,
                'deleted_at' => null,
                'created_at' => '2021-04-17 14:55:20',
                'updated_at' => '2022-11-30 11:05:15',
            ],
            [
                'id' => 94,
                'category_id' => 1,
                'name' => 'Intimzone Mann',
                'short_code' => 'IZM',
                'duration' => 30,
                'price' => 149.00,
                'deleted_at' => null,
                'created_at' => '2021-05-19 21:00:44',
                'updated_at' => '2023-03-01 15:07:27',
            ],
            [
                'id' => 95,
                'category_id' => 1,
                'name' => 'Gesäß / Po Mann',
                'short_code' => 'POM',
                'duration' => 30,
                'price' => 169.00,
                'deleted_at' => null,
                'created_at' => '2021-05-19 21:01:51',
                'updated_at' => '2023-03-01 15:07:35',
            ],
            [
                'id' => 96,
                'category_id' => 1,
                'name' => 'Pofalte Mann',
                'short_code' => 'POFM',
                'duration' => 30,
                'price' => 79.00,
                'deleted_at' => null,
                'created_at' => '2021-05-19 21:07:56',
                'updated_at' => '2023-03-01 15:07:44',
            ],
            [
                'id' => 97,
                'category_id' => 1,
                'name' => 'Dekolleté',
                'short_code' => 'DEK',
                'duration' => 15,
                'price' => 109.00,
                'deleted_at' => null,
                'created_at' => '2021-07-23 13:51:23',
                'updated_at' => '2023-03-01 15:07:54',
            ],
            [
                'id' => 98,
                'category_id' => 8,
                'name' => 'Bauch',
                'short_code' => 'BAU',
                'duration' => 30,
                'price' => 269.00,
                'deleted_at' => null,
                'created_at' => '2021-09-30 11:31:46',
                'updated_at' => '2023-03-01 15:08:01',
            ],
            [
                'id' => 99,
                'category_id' => 8,
                'name' => 'Hüfte Kryo',
                'short_code' => 'HUF',
                'duration' => 30,
                'price' => 299.00,
                'deleted_at' => null,
                'created_at' => '2021-09-30 11:32:33',
                'updated_at' => '2022-11-30 11:06:48',
            ],
            [
                'id' => 100,
                'category_id' => 3,
                'name' => 'Microneedling,Hydrafacial',
                'short_code' => 'MNHF',
                'duration' => 90,
                'price' => 399.00,
                'deleted_at' => null,
                'created_at' => '2021-10-11 14:06:19',
                'updated_at' => '2022-11-30 11:06:57',
            ],
            [
                'id' => 101,
                'category_id' => 1,
                'name' => 'Intimzone Frau',
                'short_code' => 'IZ',
                'duration' => 30,
                'price' => 69.00,
                'deleted_at' => null,
                'created_at' => '2021-10-11 16:07:17',
                'updated_at' => '2023-03-01 15:08:10',
            ],
            [
                'id' => 102,
                'category_id' => 3,
                'name' => 'Feuermale',
                'short_code' => 'FM',
                'duration' => 30,
                'price' => 199.00,
                'deleted_at' => null,
                'created_at' => '2021-12-06 07:45:00',
                'updated_at' => '2021-12-06 07:45:00',
            ],
            [
                'id' => 103,
                'category_id' => 4,
                'name' => 'TAklNano',
                'short_code' => 'TAklNa',
                'duration' => 30,
                'price' => 99.00,
                'deleted_at' => null,
                'created_at' => '2022-02-15 14:04:59',
                'updated_at' => '2022-02-15 14:04:59',
            ],
            [
                'id' => 107,
                'category_id' => 3,
                'name' => 'Microneedling RF',
                'short_code' => 'MICRF',
                'duration' => 60,
                'price' => 34.00,
                'deleted_at' => null,
                'created_at' => '2022-04-21 13:20:54',
                'updated_at' => '2023-11-08 14:44:27',
            ],
            [
                'id' => 108,
                'category_id' => 22,
                'name' => 'Dehnungstreifen',
                'short_code' => 'DEHNU',
                'duration' => 90,
                'price' => 599.00,
                'deleted_at' => null,
                'created_at' => '2022-04-21 13:23:13',
                'updated_at' => '2022-11-30 11:07:49',
            ],
            [
                'id' => 109,
                'category_id' => 1,
                'name' => 'Nase',
                'short_code' => 'Na',
                'duration' => 15,
                'price' => 49.00,
                'deleted_at' => null,
                'created_at' => '2022-04-28 13:57:53',
                'updated_at' => '2023-03-01 15:08:36',
            ],
            [
                'id' => 110,
                'category_id' => 1,
                'name' => 'Ohren',
                'short_code' => 'OH',
                'duration' => 15,
                'price' => 49.00,
                'deleted_at' => null,
                'created_at' => '2022-04-28 13:58:28',
                'updated_at' => '2023-03-01 15:08:20',
            ],
            [
                'id' => 113,
                'category_id' => 5,
                'name' => 'Profihlo',
                'short_code' => 'PROF',
                'duration' => 30,
                'price' => 319.00,
                'deleted_at' => null,
                'created_at' => '2022-10-12 15:45:11',
                'updated_at' => '2023-11-30 12:18:40',
            ],
            [
                'id' => 114,
                'category_id' => 4,
                'name' => 'Tattoo Augenbrauen',
                'short_code' => 'PiTAau',
                'duration' => 30,
                'price' => 129.00,
                'deleted_at' => null,
                'created_at' => '2023-02-10 11:43:02',
                'updated_at' => '2023-02-10 11:43:02',
            ],
            [
                'id' => 115,
                'category_id' => 1,
                'name' => 'Gesicht Unteres',
                'short_code' => 'GESU',
                'duration' => 30,
                'price' => 99.00,
                'deleted_at' => null,
                'created_at' => '2023-06-29 16:18:06',
                'updated_at' => '2023-06-29 16:18:06',
            ],
            [
                'id' => 116,
                'category_id' => 8,
                'name' => 'Fett-Weg-Spritze 2 Spritzen',
                'short_code' => 'FWS2',
                'duration' => 30,
                'price' => 279.00,
                'deleted_at' => null,
                'created_at' => '2023-07-12 18:51:34',
                'updated_at' => '2023-07-12 18:51:34',
            ],
            [
                'id' => 117,
                'category_id' => 8,
                'name' => 'Fett-Weg-Spritze 4 Spritzen',
                'short_code' => 'FWS4',
                'duration' => 30,
                'price' => 479.00,
                'deleted_at' => null,
                'created_at' => '2023-07-12 18:52:36',
                'updated_at' => '2023-07-12 18:52:36',
            ],
            [
                'id' => 118,
                'category_id' => 3,
                'name' => 'Microneedling Ges Hals Dekollete',
                'short_code' => 'MGHD',
                'duration' => 60,
                'price' => 599.00,
                'deleted_at' => null,
                'created_at' => '2023-07-12 18:54:34',
                'updated_at' => '2023-11-08 14:44:17',
            ],
            [
                'id' => 119,
                'category_id' => 1,
                'name' => 'Kopf',
                'short_code' => 'KPF',
                'duration' => 30,
                'price' => 149.00,
                'deleted_at' => null,
                'created_at' => '2023-07-27 12:47:43',
                'updated_at' => '2023-07-27 12:48:14',
            ],
            [
                'id' => 120,
                'category_id' => 1,
                'name' => 'Po Frau',
                'short_code' => 'PO',
                'duration' => 30,
                'price' => 119.00,
                'deleted_at' => null,
                'created_at' => '2023-10-19 14:00:47',
                'updated_at' => '2023-10-19 14:00:47',
            ],
            [
                'id' => 121,
                'category_id' => 1,
                'name' => 'Rasur',
                'short_code' => 'RAS',
                'duration' => 0,
                'price' => 20.00,
                'deleted_at' => null,
                'created_at' => '2023-11-09 13:44:40',
                'updated_at' => '2023-11-09 13:44:40',
            ],
            [
                'id' => 122,
                'category_id' => 17,
                'name' => 'Äderchen+Rosacea / Wangen und Nase',
                'short_code' => 'Ä+R/W+N',
                'duration' => 30,
                'price' => 229.00,
                'deleted_at' => null,
                'created_at' => '2023-11-30 16:02:43',
                'updated_at' => '2023-11-30 16:02:43',
            ],
            [
                'id' => 123,
                'category_id' => 17,
                'name' => 'Rosacea / Couperose',
                'short_code' => 'Rc/Cr',
                'duration' => 30,
                'price' => 169.00,
                'deleted_at' => null,
                'created_at' => '2023-11-30 16:04:14',
                'updated_at' => '2023-11-30 16:04:14',
            ],
            [
                'id' => 124,
                'category_id' => 17,
                'name' => 'Teleangiektasien Nase',
                'short_code' => 'Tn',
                'duration' => 30,
                'price' => 139.00,
                'deleted_at' => null,
                'created_at' => '2023-11-30 16:05:07',
                'updated_at' => '2023-11-30 16:05:07',
            ],
            [
                'id' => 125,
                'category_id' => 17,
                'name' => 'Besenreiser Wangenbereich komplett ',
                'short_code' => 'BWk',
                'duration' => 30,
                'price' => 179.00,
                'deleted_at' => null,
                'created_at' => '2023-11-30 16:05:53',
                'updated_at' => '2023-11-30 16:05:53',
            ],
            [
                'id' => 126,
                'category_id' => 17,
                'name' => 'Besenreiser gesamtes Gesicht inkl.Nase',
                'short_code' => 'BrgG+N',
                'duration' => 30,
                'price' => 299.00,
                'deleted_at' => null,
                'created_at' => '2023-11-30 16:06:50',
                'updated_at' => '2023-11-30 16:06:50',
            ],
        ], ['id']);
    }
}
